version: '3'
services:
  beetroot:
    image: beetroot
    build:
      context: ../exercise02/
    ports:
      - "${PORT1}:8080"
    volumes:
      - ./.secretFile.txt:/tmp/.secretFile.txt
    environment:
      - TZ=Europe/Oslo
      - HackerLeetC0d3="test"
  
  caddy:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
