#cloud-config
package_update: true
package_upgrade: true
packages:
  - python-is-python3
  - neofetch
  - htop
  - docker-ce
  - docker-ce-cli
  - docker-compose
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
users:
  - name: docker
    groups: sudo
    homedir: /custom/home/dir
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
  - name: Mallory
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: Eve
    groups: docker
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: default
    groups: sudo, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
  - touch /etc/docker/daemon.json
  - echo '{"mtu" ':' 1442}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker.service
  - sudo swapoff -a
  - echo "vm.max_map_count=262144" | sudo tee /etc/sysctl.conf
  - sudo sysctl -p 
  - [wget, https://raw.githubusercontent.com/opensearch-project/documentation-website/2.6/assets/examples/docker-compose.yml]
  - sudo docker-compose up -d

  
  


