Vagrant.configure("2") do |config|
    config.env.enable # enable .env support plugin (it will let us easily enable cloud_init support)
    config.vm.network "forwarded_port", guest: 5601, host: 5601
    config.vm.provider "virtualbox" do |v|
      v.memory = 5048
      v.cpus = 2
    end
    config.vm.box = "ubuntu/jammy64"
    config.vm.cloud_init :user_data do |cloud_init|
      cloud_init.content_type = "text/cloud-config"
      cloud_init.path = "cloudinit.yml"
    end
    
end

