Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end
  # redis
  config.vm.define "redis" do |redis|
    redis.vm.box = "boxomatic/centos-stream-9"
    redis.vm.network "private_network", ip: "192.168.56.17"
  end 
  #maria
  config.vm.define "mariadb" do |mariadb|
    mariadb.vm.box = "boxomatic/centos-stream-9"
    mariadb.vm.network "private_network", ip: "192.168.56.18"
  end
  config.vm.define "ctfd" do |ctfd|
    ctfd.vm.box = "boxomatic/centos-stream-9"
    ctfd.vm.network "private_network", ip: "192.168.56.16" 
  end
  #nginx
  config.vm.define "nginx" do |nginx|
    nginx.vm.box = "boxomatic/centos-stream-9"
    nginx.vm.network "private_network", ip: "192.168.56.19"
    nginx.vm.network "forwarded_port", guest: 80, host: 80
  end
    config.vm.provision "ansible" do |ansible|
      ansible.inventory_path = "hosts.ini"
      ansible.playbook = "site.yaml"
  end
end

