services:
  beetroot:
    image: beetroot
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./.secretFile.txt:/tmp/.secretFile.txt/
    environment:
      - TZ=Europe/Oslo
      - HackerLeetC0d3="pang"
