- name: Start MariaDB Docker container
  docker_container:
    name: mariadb
    image: mariadb:latest
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: ctfd
      MYSQL_DATABASE: ctfd
      MYSQL_USER: ctfd
      MYSQL_PASSWORD: ctfd
    ports:
      - "3306:3306"